const {test} = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs'), os = require('node:os'), path = require('node:path');
const {randomUUID, randomBytes} = require('node:crypto');
process.env.USE_MOCK_DB = 'true';
process.env.JWT_SECRET = randomBytes(32).toString('hex');
process.env.WHATSAPP_DB_PATH = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'commit-connected-')), 'demo.sqlite');
const {prisma} = require('../src/config/database');
test('chat to customer to quotation to order to invoice and payments stays linked, safe to retry and persistent', async t => {
  const app = require('express')();
  app.use(require('express').json());
  for (const [mount, file] of [['manual','manualCRM'], ['orders','orderRoutes'], ['invoices','invoiceRoutes'], ['payments','paymentRoutes']]) app.use('/api/' + mount, require('../src/routes/' + file));
  app.use(require('../src/middleware/errorHandler'));
  const server = app.listen(0, '127.0.0.1');
  await new Promise(resolve => server.once('listening', resolve));
  t.after(() => new Promise(resolve => server.close(resolve)));
  const users = await prisma.user.findMany({});
  const call = async (method, route, body, role = 'ADMIN') => {
    const token = require('jsonwebtoken').sign({userId: users.find(u => u.role === role).id}, process.env.JWT_SECRET);
    const r = await fetch('http://127.0.0.1:' + server.address().port + '/api/' + route, {method, headers: {'Content-Type': 'application/json', Authorization: 'Bearer ' + token}, body: body ? JSON.stringify(body) : undefined});
    return {status: r.status, data: await r.json()};
  };
  const {store} = require('../src/services/whatsapp');
  const chat = await store.transaction(s => s.conversation('919876543291', {}));
  const input = {companyName: 'Connected demo buyer', contactPerson: 'Demo contact', mobile: '+919999999999'};
  assert.equal((await call('POST', 'manual/chats/' + chat.id + '/customer', input, 'MARKETING')).status, 403);
  const first = await call('POST', 'manual/chats/' + chat.id + '/customer', input);
  assert.equal(first.status, 200);
  const customer = first.data.customer;
  assert.equal(customer.mobile, '+919876543291'); // Cannot replace the chat number in a forged form.
  assert.equal((await store.getConversation(chat.id)).customerId, customer.id);
  const repeated = await Promise.all([1,2].map(() => call('POST', 'manual/chats/' + chat.id + '/customer', input)));
  assert.ok(repeated.every(r => r.data.customer.id === customer.id));
  assert.equal((await call('POST', 'manual/chats/' + chat.id + '/customer', input, 'SALES')).status, 403);
  const quote = (await call('POST', 'manual/quotations', {customerId: customer.id, items: [{description: 'Demo shirts', quantity: 1, unitPrice: 100}], taxPercent: 18})).data.quotation;
  assert.equal((await call('POST', 'orders/from-quotation', {quotationId: quote.id}, 'SALES')).status, 403);
  const order = (await call('POST', 'orders/from-quotation', {quotationId: quote.id})).data.order;
  assert.equal((await call('POST', 'orders/from-quotation', {quotationId: quote.id})).data.order.id, order.id);
  await call('PUT', 'orders/' + order.id, {status: 'CONFIRMED'});
  const invoice = (await call('POST', 'invoices/from-order', {orderId: order.id})).data.invoice;
  assert.ok(invoice.id);
  let flow = (await call('GET', 'manual/workflow/quotations/' + quote.id)).data;
  assert.equal(flow.customer.id, customer.id); assert.equal(flow.order.id, order.id); assert.equal(flow.invoice.id, invoice.id);
  assert.equal((await call('GET', 'manual/workflow/invoices/' + invoice.id, undefined, 'SALES')).status, 403);
  const route = 'manual/invoices/' + invoice.id + '/payment';
  const payment = {amount: 50, method: 'UPI', paymentDate: '2026-10-07', referenceNumber: 'PAY-' + randomUUID()};
  for (const invalid of [{amount: 'NaN'}, {amount: -1}, {amount: 0.001}, {amount: 100000}, {method: 'OTHER'}, {paymentDate: '2026-02-30'}]) assert.equal((await call('POST', route, {...payment, ...invalid})).status, 400);
  assert.equal((await call('POST', route, payment, 'MARKETING')).status, 403);
  assert.equal((await call('POST', route, payment, 'SALES')).status, 403);
  // A failure between the payment insert and balance update rolls both back.
  const original = prisma.invoice.update;
  prisma.invoice.update = async () => {throw new Error('Simulated write failure');};
  assert.equal((await call('POST', route, payment)).status, 500);
  prisma.invoice.update = original;
  assert.equal((await prisma.payment.findMany({where: {invoiceId: invoice.id}})).length, 0);
  const results = await Promise.all([1,2].map(() => call('POST', route, payment)));
  assert.deepEqual(results.map(r => r.status).sort(), [200,201]);
  assert.equal((await call('POST', route, {...payment, amount: 51})).status, 409);
  flow = (await call('GET', 'manual/workflow/orders/' + order.id)).data;
  assert.equal(flow.invoice.amountPaid, 50); assert.equal(flow.invoice.status, 'PARTIALLY_PAID');
  assert.equal((await call('GET', 'payments/invoice/' + invoice.id, undefined, 'SALES')).status, 403);
  // Two different attempts cannot both spend the same remaining balance.
  const amount = flow.invoice.balanceDue;
  const concurrent = await Promise.all([1,2].map(() => call('POST', route, {...payment, amount, referenceNumber: 'PAY-' + randomUUID()})));
  assert.deepEqual(concurrent.map(r => r.status).sort(), [201,400]);
  const history = (await call('GET', 'manual/customers/' + customer.id + '/history')).data;
  assert.equal(history.chats[0].id, chat.id); assert.equal(history.documents.invoices[0].balanceDue, 0);
  const child = require('node:child_process').spawnSync(process.execPath, ['-e', "const {prisma}=require('./src/config/database'); Promise.all([prisma.invoice.findUnique({where:{id:process.env.TEST_INVOICE_ID}}),prisma.payment.findMany({where:{invoiceId:process.env.TEST_INVOICE_ID}})]).then(([i,p])=>console.log(JSON.stringify({paid:i.amountPaid,balance:i.balanceDue,status:i.status,payments:p.length})))"], {cwd: path.resolve(__dirname, '..'), env: {...process.env, TEST_INVOICE_ID: invoice.id}, encoding: 'utf8'});
  assert.equal(child.status, 0, child.stderr);
  assert.match(child.stdout, /"balance":0,"status":"PAID","payments":2/);
});
